blank_issues_enabled: false
contact_links:
  - name: Homebridge Discord Channel for AirNow
    url: https://discord.gg/8fpZA4S
    about: Please ask and answer questions here.
  - name: Homebridge-air - Pull Requests
    url: https://github.com/donavanbecker/homebridge-air/pulls
    about: Please report security vulnerabilities here.
